default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ab
  password: monster21
  host: localhost

development:
  <<: *default
  database: albatross_development

test:
  <<: *default
  database: albatross_test

production:
  <<: *default
  # database: albatross_production
  # username: your_production_username
  # password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
