default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
  username: ab
  password: '@1b@tr0$$'
  host: localhost

development:
  <<: *default
  database: albatross_development

test:
  <<: *default
  database: albatross_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
